# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Use Calendar

defaults:
  run:
    working-directory: packages/react-use-calendar-component

on:
  push:
    branches: ['main']
    paths: ['packages/react-use-calendar-component']
  pull_request:
    branches: ['main']
    paths: ['packages/react-use-calendar-component']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.13.2
      - run: pnpm install
      - run: pnpm test
